/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module "vue-router/auto-routes" {
  import type {
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
    RouteRecordInfo,
  } from "vue-router";

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    "/about": RouteRecordInfo<
      "/about",
      "/about",
      Record<never, never>,
      Record<never, never>
    >;
    "/dashboard/": RouteRecordInfo<
      "/dashboard/",
      "/dashboard",
      Record<never, never>,
      Record<never, never>
    >;
    "/dev": RouteRecordInfo<
      "/dev",
      "/dev",
      Record<never, never>,
      Record<never, never>
    >;
    "/home": RouteRecordInfo<
      "/home",
      "/home",
      Record<never, never>,
      Record<never, never>
    >;
    "/md-cv/": RouteRecordInfo<
      "/md-cv/",
      "/md-cv",
      Record<never, never>,
      Record<never, never>
    >;
    "/pdf-cv/": RouteRecordInfo<
      "/pdf-cv/",
      "/pdf-cv",
      Record<never, never>,
      Record<never, never>
    >;
    "/settings": RouteRecordInfo<
      "/settings",
      "/settings",
      Record<never, never>,
      Record<never, never>
    >;
  }
}
