// Generate the reserved-username set: names a user may NOT take as their `nik`,
// because the username space is the site's root namespace (see memory
// seewe-core-link-concept) and to block impersonation/offensive handles.
//
// Sources (union, lowercased, deduped):
//   1. our own app route slugs  — read locally from src/pages (authoritative;
//      regenerate when routes change so a nik can't shadow /dashboard etc.)
//   2. curated infra/role/brand set  — baked in below
//   3. external lists (best-effort fetch; skipped offline):
//        - The Big Username Blacklist (marteinn, MIT)
//        - LDNOOBW bad-words (en)
//
// Output: api/utils/reserved_usernames.gen.ts (a sorted ReadonlySet literal).
//
// Run (from api/):  deno run -A dev/gen_reserved_usernames.ts

import { join } from "@std/path"

const api_root = join(import.meta.dirname ?? ".", "..")
const repo_root = join(api_root, "..")

// --- 1. app route slugs (top-level segments of the file-based router) ---------
const route_slugs = async (): Promise<string[]> => {
  const dir = join(repo_root, "src", "pages")
  const slugs: string[] = []
  try {
    for await (const e of Deno.readDir(dir)) {
      if (e.isDirectory) slugs.push(e.name)
      else if (e.name.endsWith(".vue")) slugs.push(e.name.slice(0, -4))
    }
  } catch (err) {
    console.warn(`! could not read ${dir}: ${(err as Error).message}`)
  }
  return slugs
}

// --- 2. curated infra / role / brand / future-route reservations --------------
const CURATED = [
  // api + infra prefixes actually served under root
  "v1", "openapi", "id", "content", "auth", "users", "page", "mdcv", "json",
  "assets", "static", "public", "favicon", "robots", "sitemap", "well-known",
  "api", "www", "cdn", "app", "navigate",
  // account / auth routes we will likely add
  "login", "logout", "signin", "signout", "signup", "register", "account",
  "profile", "me", "settings",
  // marketing / legal we may add
  "about", "home", "terms", "privacy", "pricing", "blog", "docs", "faq", "help",
  // roles / brand / impersonation + RFC 2142 role mailboxes
  "admin", "administrator", "root", "support", "contact", "official", "staff",
  "team", "system", "security", "abuse", "billing", "status", "mod",
  "moderator", "postmaster", "webmaster", "hostmaster", "noc", "anonymous",
  "everyone", "null", "undefined", "none", "owner", "seewe",
]

// --- 3. external lists (best-effort) ------------------------------------------
type Source = { name: string; urls: string[]; parse: (t: string) => string[] }

const EXTERNAL: Source[] = [
  {
    name: "the-big-username-blacklist",
    urls: [
      "https://raw.githubusercontent.com/marteinn/The-Big-Username-Blacklist/main/list.json",
      "https://raw.githubusercontent.com/marteinn/The-Big-Username-Blacklist/master/list.json",
    ],
    parse: (t) => JSON.parse(t) as string[],
  },
  {
    name: "ldnoobw-en",
    urls: [
      "https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en",
    ],
    parse: (t) => t.split("\n"),
  },
]

const fetch_source = async (s: Source): Promise<string[]> => {
  for (const url of s.urls) {
    try {
      const res = await fetch(url)
      if (!res.ok) continue
      const words = s.parse(await res.text())
      console.log(`  + ${s.name}: ${words.length}`)
      return words
    } catch { /* try next url */ }
  }
  console.warn(`  ! ${s.name}: unreachable, skipped`)
  return []
}

// --- build --------------------------------------------------------------------
const normalize = (raw: string) => raw.trim().toLowerCase()

const set = new Set<string>()
const add_all = (words: string[]) => {
  for (const w of words) {
    const n = normalize(w)
    if (n) set.add(n)
  }
}

const slugs = await route_slugs()
console.log(`  + app route slugs: ${slugs.length} (${slugs.join(", ")})`)
add_all(slugs)
add_all(CURATED)
for (const s of EXTERNAL) add_all(await fetch_source(s))

const sorted = [...set].sort()
const body = `// GENERATED by api/dev/gen_reserved_usernames.ts — DO NOT EDIT.
// ${sorted.length} reserved usernames (app slugs + curated + external lists).
// Regenerate when routes change or to refresh the external lists.
export const RESERVED_USERNAMES: ReadonlySet<string> = new Set([
${sorted.map((w) => `  ${JSON.stringify(w)},`).join("\n")}
])
`

const out = join(api_root, "utils", "reserved_usernames.gen.ts")
await Deno.writeTextFile(out, body)
console.log(`wrote ${sorted.length} reserved usernames -> ${out}`)
